import type { NextPage } from 'next'
import Head from 'next/head'
import AnnoyingHeads from '../components/heads/AnnoyingHeads'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Annoying CSS Heads</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          All over the viewport!
        </h1>
      </main>

      <AnnoyingHeads />

    </div>
  )
}

export default Home
